version: "3.7"
services:
  app:
    build: .
    ports: 
      - "8080:8080"
    depends_on:
      - mongo
    volumes:
      - ./:/usr/src/app
    command: [ "npm", "run", "dev" ]

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
